"""THE anti-circularity guard. Freeze this BEFORE writing any probe.

SYN must find the planted faults WITHOUT being told where they are. If telemetry
were generated by a model we chose and then 'detected', we would have proven
nothing. Run with: pytest validation/blind_detection_test.py -v
"""
from __future__ import annotations
from typing import List

import numpy as np
import pytest

from complexity.detonation_estimator import estimate
from complexity.symbolic_regressor import fit as fit_law
from shared.types import RiskLevel
from stability.basin_detector import critical_load, detect
from synthesis.simulator import RetryLoopTwin
from telemetry.multiscale_sweep import MultiScaleData, build as build_ms
from telemetry.recorder import Recorder
from validation.injected_faults import by_id
from validation.metrics import DetectionOutcome, score

LOADS = [0.5 * i for i in range(1, 13)]


@pytest.fixture(scope="module")
def twin() -> RetryLoopTwin:
    """The Twin as SYN builds it -- fit to the sample app's telemetry if present."""
    return RetryLoopTwin()


def test_metastable_fault_detected_blind(twin):
    """SYN is given ONLY the Twin and a load range -- never the fault location."""
    fault = by_id("retry_storm")
    found = [L for L in LOADS if detect(twin, L).bistable]
    assert found, "no metastable basin found anywhere in the load range"
    cl = min(found)
    assert cl <= fault.expect["max_critical_load"], (
        f"death-spiral threshold {cl} above the planted fault's expected range")
    ev = detect(twin, cl)
    assert ev.margin is not None, "bistable but no separatrix margin computed"


def test_margin_shrinks_with_load(twin):
    """The early-warning signal must be monotone: as load rises toward the critical
    point, the healthy basin's margin must shrink."""
    margins = []
    for L in LOADS:
        ev = detect(twin, L)
        if ev.bistable and ev.margin is not None:
            margins.append((L, ev.margin))
    assert len(margins) >= 2, "not enough bistable loads to test monotonicity"
    assert margins[-1][1] <= margins[0][1] + 1e-6, (
        f"margin did not shrink with load: {margins}")


def test_hysteresis_is_real(twin):
    """Same load, different history -> different settled state. This is what
    threshold monitoring cannot see."""
    load = 3.0
    from_empty = float(twin.settle(np.array([0.0]), load)[0])
    from_stressed = float(twin.settle(np.array([twin.ceiling() or 50.0]), load)[0])
    assert abs(from_empty - from_stressed) > 1.0, (
        "no hysteresis: the system recovers regardless of history")


def test_complexity_fault_detected_blind():
    """PySR/basis fit must recover the planted quadratic from telemetry alone."""
    fault = by_id("n_plus_one")
    rows = Recorder().read("multiscale")
    if not rows:
        pytest.skip("no multiscale telemetry captured; run the load driver first")
    ms = build_ms(rows)
    law = fit_law(ms)
    assert law.sufficient_evidence, f"insufficient evidence: {law.note}"
    assert law.complexity_class == fault.expect["complexity_class"], (
        f"expected {fault.expect['complexity_class']}, got {law.complexity_class}")
    assert law.r2 >= fault.expect["min_r2"], f"poor fit: R^2={law.r2}"


def test_insufficient_spread_reports_unknown():
    """The honest non-answer: thin data must NEVER produce a fabricated law."""
    n = np.array([1000.0, 1100.0, 1200.0])          # <1 decade of spread
    ms = MultiScaleData(n, n ** 2 * 1e-6, "elapsed_s")
    law = fit_law(ms)
    assert not law.sufficient_evidence
    assert estimate(law).crossing_n is None


def test_clean_code_is_not_flagged(twin):
    """False-positive guard: a well-behaved config must not trip the gate."""
    calm = RetryLoopTwin(gain=0.2, thresh=50.0, cap=20.0)
    assert not detect(calm, 1.0).bistable, "flagged a stable system as metastable"